models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
          severity: error

    columns:
      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: The host's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - accepted_values:
              arguments:
                values:
                  - 'Entire home/apt'
                  - 'Private room'
                  - 'Shared room'
                  - 'Hotel room'

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts.
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
        data_tests:
          - not_null
          - unique

      - name: host_name
        data_type: string
        data_tests:
          - not_null

      - name: is_superhost
        data_type: string
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']

      - name: created_at
        data_type: timestamp

      - name: updated_at
        data_type: timestamp

  - name: fct_reviews
    description: Fact table containing Airbnb reviews.
    columns:
      - name: listing_id
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_listings_cleansed')
                field: listing_id

      - name: reviewer_name
        data_tests:
          - not_null

      - name: review_sentiment
        data_tests:
          - accepted_values:
              arguments:
                values: ['positive', 'neutral', 'negative']
